TEMPLATE = app
TARGET = medit
QT += core \
    gui \
    sql \
    xml
HEADERS += item/DistanceLinkItem.h \
    asterix/lib/Base64.h \
    asterix/cat021/ADSBCls.h \
    asterix/cat021/Cat021.h \
    asterix/cat021/TrajectoryIntent.h \
    trackrpt/ReportOption.h \
    trackrpt/TrackReportOption.h \
    trackrpt/TrackThread.h \
    trackrpt/VerticalViewControl.h \
    trackrpt/VerticalViewItem.h \
    trackrpt/VerticalView.h \
    lib/GlobalColor.h \
    trackrpt/LegendItem.h \
    trackrpt/TrackPreview.h \
    trackrpt/TrackData.h \
    lib/AirPlaneModel.h \
    trackrpt/TrackDataModel.h \
    lib/TrackViewQueryModel.h \
    lib/SymbolTypeCombo.h \
    lib/ColorTypeCombo.h \
    lib/CustomItemDelegate.h \
    trackrpt/TrackViewSelection.h \
    lib/DbManager.h \
    trackrpt/CreateTrackProcess.h \
    asterix/DecodeAsterix.h \
    asterix/cat004/AircraftIdentification.h \
    asterix/cat004/Cat004.h \
    asterix/cat004/SafetyNets.h \
    asterix/cat062/AircraftDerivedData.h \
    asterix/cat062/Cat062.h \
    asterix/cat062/EstimatedAccuracy.h \
    asterix/cat062/FlightPlanData.h \
    asterix/cat062/MeasuredInfo.h \
    asterix/cat062/Mode3A.h \
    asterix/cat062/Mode5.h \
    asterix/cat062/ModeSMBData.h \
    asterix/cat062/SystemTrack.h \
    asterix/cat062/SystemTrackUpdateAge.h \
    asterix/cat062/TimeOfDepArrData.h \
    asterix/cat062/TrackDataAge.h \
    asterix/cat062/TrackStatus.h \
    asterix/cat062/TrajectoryIntentData.h \
    asterix/lib/AsterixLib.h \
    asterix/lib/BaseTypes.h \
    asterix/lib/CBuffer.h \
    asterix/lib/CTrackTime.h \
    asterix/lib/GlobalConsts.h \
    trackrpt/createtrackreport.h \
    item/AUserLayerItemMng.h \
    item/LinkItem.h \
    item/AirPlaneTextItem.h \
    item/AirPlaneItem.h \
    item/DirBearing.h \
    lib/ManualCoordEdit.h \
    lib/XpmPickerDialog.h \
    item/UserDrawItem.h \
    rightlayout/CheckListBox.h \
    rightlayout/InputUserText.h \
    rightlayout/EditDefine.h \
    lib/ColorRgbPicker.h \
    lib/FillPatternCombo.h \
    lib/LineTypeCombo.h \
    rightlayout/RightPanel.h \
    item/ViewPortItem.h \
    item/AHoldLayerItem.h \
    item/AUserDefinedMapList.h \
    AMap.h \
    lib/CheckClickLabel.h \
    leftlayout/IdCheckBox.h \
    leftlayout/LayerDetailsPanel.h \
    lib/AUserDefinedLayer.h \
    lib/AUserDefinedMap.h \
    item/AUserLayerItem.h \
    item/ASymbolLayerItem.h \
    item/APointLayerItem.h \
    lib/ConfigParser.h \
    lib/MapUtil.h \
    lib/GraphicsUtils.h \
    lib/AirDraw.h \
    lib/CalcAir.h \
    item/ALinesLayerItem.h \
    lib/UnitChange.h \
    lib/MapConvertFunc.h \
    lib/AMapconf.h \
    item/AreaLayerItem.h \
    lib_layer/LayerProperty.h \
    lib_layer/MsbBound.h \
    lib_layer/ALayer.h \
    lib/Log424.h \
    lib_layer/LayerDefine.h \
    lib_layer/ClickableLabel.h \
    lib_layer/LayerCheckBox.h \
    lib_layer/MapDefine.h \
    leftlayout/UserDefineMapPanel.h \
    leftlayout/MapLayerDetailPanel.h \
    leftlayout/MapLayerPanel.h \
    leftlayout/LeftPanel.h \
    item/BearingCircleItem.h \
    lib/Turtle.h \
    item/LatLonItem.h \
    lib/NorthGreenichPoint.h \
    lib/usermathutil.h \
    lib/LatLonBound.h \
    lib/LatLonConvert.h \
    lib/CenterCoord.h \
    MapCanvas.h \
    GeoData.h \
    GenerateView.h \
    mapview.h
SOURCES += item/DistanceLinkItem.cpp \
    asterix/lib/Base64.cpp \
    asterix/cat021/ADSBCls.cpp \
    asterix/cat021/Cat021.cpp \
    asterix/cat021/TrajectoryIntent.cpp \
    trackrpt/ReportOption.cpp \
    trackrpt/TrackReportOption.cpp \
    trackrpt/TrackThread.cpp \
    trackrpt/VerticalViewControl.cpp \
    trackrpt/VerticalViewItem.cpp \
    trackrpt/VerticalView.cpp \
    trackrpt/LegendItem.cpp \
    trackrpt/TrackPreview.cpp \
    trackrpt/TrackData.cpp \
    lib/AirPlaneModel.cpp \
    trackrpt/TrackDataModel.cpp \
    lib/TrackViewQueryModel.cpp \
    lib/SymbolTypeCombo.cpp \
    lib/ColorTypeCombo.cpp \
    lib/CustomItemDelegate.cpp \
    trackrpt/TrackViewSelection.cpp \
    lib/DbManager.cpp \
    trackrpt/CreateTrackProcess.cpp \
    asterix/DecodeAsterix.cpp \
    asterix/cat004/AircraftIdentification.cpp \
    asterix/cat004/Cat004.cpp \
    asterix/cat004/SafetyNets.cpp \
    asterix/cat062/AircraftDerivedData.cpp \
    asterix/cat062/Cat062.cpp \
    asterix/cat062/EstimatedAccuracy.cpp \
    asterix/cat062/FlightPlanData.cpp \
    asterix/cat062/MeasuredInfo.cpp \
    asterix/cat062/Mode3A.cpp \
    asterix/cat062/Mode5.cpp \
    asterix/cat062/ModeSMBData.cpp \
    asterix/cat062/SystemTrack.cpp \
    asterix/cat062/SystemTrackUpdateAge.cpp \
    asterix/cat062/TimeOfDepArrData.cpp \
    asterix/cat062/TrackDataAge.cpp \
    asterix/cat062/TrackStatus.cpp \
    asterix/cat062/TrajectoryIntentData.cpp \
    asterix/lib/AsterixLib.cpp \
    asterix/lib/CBuffer.cpp \
    asterix/lib/CTrackTime.cpp \
    trackrpt/createtrackreport.cpp \
    item/AUserLayerItemMng.cpp \
    item/LinkItem.cpp \
    item/AirPlaneTextItem.cpp \
    item/AirPlaneItem.cpp \
    item/DirBearing.cpp \
    lib/ManualCoordEdit.cpp \
    lib/XpmPickerDialog.cpp \
    item/UserDrawItem.cpp \
    rightlayout/CheckListBox.cpp \
    rightlayout/InputUserText.cpp \
    lib/ColorRgbPicker.cpp \
    lib/FillPatternCombo.cpp \
    lib/LineTypeCombo.cpp \
    rightlayout/RightPanel.cpp \
    item/ViewPortItem.cpp \
    item/AHoldLayerItem.cpp \
    item/AUserDefinedMapList.cpp \
    AMap.cpp \
    lib/CheckClickLabel.cpp \
    leftlayout/IdCheckBox.cpp \
    leftlayout/LayerDetailsPanel.cpp \
    lib/AUserDefinedLayer.cpp \
    lib/AUserDefinedMap.cpp \
    item/AUserLayerItem.cpp \
    item/ASymbolLayerItem.cpp \
    item/APointLayerItem.cpp \
    lib/ConfigParser.cpp \
    lib/MapUtil.cpp \
    lib/GraphicsUtils.cpp \
    lib/AirDraw.cpp \
    lib/CalcAir.cpp \
    item/ALinesLayerItem.cpp \
    lib/AMapconf.cpp \
    item/AreaLayerItem.cpp \
    lib_layer/LayerProperty.cpp \
    lib/Log424.cpp \
    lib_layer/LayerDefine.cpp \
    leftlayout/UserDefineMapPanel.cpp \
    leftlayout/MapLayerDetailPanel.cpp \
    leftlayout/MapLayerPanel.cpp \
    leftlayout/LeftPanel.cpp \
    item/BearingCircleItem.cpp \
    lib/Turtle.cpp \
    item/LatLonItem.cpp \
    lib/NorthGreenichPoint.cpp \
    lib/LatLonBound.cpp \
    lib/LatLonConvert.cpp \
    lib/CenterCoord.cpp \
    MapCanvas.cpp \
    GenerateView.cpp \
    main.cpp \
    mapview.cpp
FORMS += trackrpt/TrackReportOption.ui \
    trackrpt/VerticalView.ui \
    trackrpt/TrackPreview.ui \
    trackrpt/TrackViewSelection.ui \
    trackrpt/createtrackreport.ui
RESOURCES += mapview.qrc
INCLUDEPATH = /home/altibase/altibase_home/include
LIBS += -L/home/altibase/altibase_home/lib \
    -lpthread \
    -lodbccli \
    -lcrypt
